import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/lahan_model.dart';
import '../services/lahan_service.dart';

// ─── Lahan State ─────────────────────────────────────────

class LahanState {
  const LahanState({
    this.lahanList = const [],
    this.isLoading = false,
    this.error,
  });

  final List<LahanModel> lahanList;
  final bool isLoading;
  final String? error;

  LahanState copyWith({
    List<LahanModel>? lahanList,
    bool? isLoading,
    String? error,
  }) {
    return LahanState(
      lahanList: lahanList ?? this.lahanList,
      isLoading: isLoading ?? this.isLoading,
      error: error,
    );
  }
}

// ─── Lahan Notifier ──────────────────────────────────────

class LahanNotifier extends StateNotifier<LahanState> {
  LahanNotifier() : super(const LahanState());

  final _service = LahanService.instance;

  /// Load all lahan from service.
  Future<void> loadAll() async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      final list = await _service.getAll();
      state = LahanState(lahanList: list);
    } catch (e) {
      debugPrint('[LahanNotifier] loadAll error: $e');
      state = state.copyWith(
        isLoading: false,
        error: 'Gagal memuat daftar lahan',
      );
    }
  }

  /// Add a new lahan.
  Future<bool> add({
    required String name,
    required String tanaman,
    required double luas,
    required String satuanLuas,
    required String emoji,
    DateTime? tanggalTanam,
    String fase = 'Persiapan',
  }) async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      final lahan = LahanModel(
        id: '', // will be generated by service
        userId: 'mock_user',
        name: name,
        tanaman: tanaman,
        luas: luas,
        satuanLuas: satuanLuas,
        emoji: emoji,
        tanggalTanam: tanggalTanam,
        fase: fase,
      );
      await _service.add(lahan);
      await loadAll(); // refresh list
      return true;
    } catch (e) {
      state = state.copyWith(
        isLoading: false,
        error: 'Gagal menambahkan lahan',
      );
      return false;
    }
  }

  /// Update an existing lahan.
  Future<bool> update(LahanModel lahan) async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      await _service.update(lahan);
      await loadAll();
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, error: 'Gagal mengubah lahan');
      return false;
    }
  }

  /// Delete a lahan.
  Future<bool> delete(String id) async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      await _service.delete(id);
      await loadAll();
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, error: 'Gagal menghapus lahan');
      return false;
    }
  }

  /// Clear error.
  void clearError() {
    state = state.copyWith(error: null);
  }
}

// ─── Providers ───────────────────────────────────────────

final lahanProvider = StateNotifierProvider<LahanNotifier, LahanState>((ref) {
  final notifier = LahanNotifier();
  // Auto-load on creation
  notifier.loadAll();
  return notifier;
});
